# Generated by Django 5.0.6 on 2024-06-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="looker",
            name="languages",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
