# Generated by Django 5.0.6 on 2024-06-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_looker_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="looker",
            name="languages",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
