# Generated by Django 5.0.6 on 2024-06-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_looker_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lookersocial",
            old_name="link",
            new_name="url",
        ),
        migrations.RenameField(
            model_name="platform",
            old_name="link",
            new_name="url",
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
