# Generated by Django 5.0.6 on 2024-06-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_link_lookersocial_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lookersocial",
            name="url",
        ),
        migrations.AddField(
            model_name="lookersocial",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
